"""HTML/CSS/JS templates for the PyPaCER report."""

from datetime import datetime
from pathlib import Path


def build_report_html(
    ct_file: str,
    timestamp: str,
    summary_html: str,
    plot_3d_html: str,
    volume_rendering_html: str,
    json_formatted: str,
    mini_json_formatted: str,
    include_volume_rendering: bool,
    has_orientation: bool = False,
    orientation_html: str = "",
    version: str = "",
) -> str:
    """Assemble the complete HTML report from its sections."""
    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>PyPaCER Reconstruction Report</title>
        <meta charset="utf-8">
        <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
        <style>
{_get_css()}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>PyPaCER Reconstruction Report</h1>
                <p>CT File: {Path(ct_file).name} | Generated: {timestamp}</p>
            </div>

            <div class="tabs">
                <div class="tab active" onclick="showTab('summary')">Summary</div>
                {('<div class="tab" onclick="showTab(' + "'orientation'" + ')">Orientation</div>') if has_orientation else ""}
                <div class="tab" onclick="showTab('visualization3d')">3D Visualization</div>
                {('<div class="tab" onclick="showTab(' + "'volume'" + ')">Volume Rendering</div>') if include_volume_rendering else ""}
                <div class="tab" onclick="showTab('minijson')">Mini JSON</div>
                <div class="tab" onclick="showTab('json')">Raw JSON</div>
            </div>

            <div id="summary" class="tab-content active">
                {summary_html}
            </div>

            {('<div id="orientation" class="tab-content">' + orientation_html + '</div>') if has_orientation else ""}

            <div id="visualization3d" class="tab-content">
                {plot_3d_html}
            </div>

            {('<div id="volume" class="tab-content">') if include_volume_rendering else ""}
            {volume_rendering_html if include_volume_rendering else ""}
            {"</div>" if include_volume_rendering else ""}

            <div id="minijson" class="tab-content">
                <div class="json-container">
                    <h2>Core Reconstruction Data (Mini)</h2>
                    <p style="color: #666; margin-bottom: 10px;">Contact positions, orientation, and metadata only — no intensity profiles or trajectory samples.</p>
                    <div class="json-content">{mini_json_formatted}</div>
                </div>
            </div>

            <div id="json" class="tab-content">
                <div class="json-container">
                    <h2>Raw Reconstruction Data</h2>
                    <div class="json-content">{json_formatted}</div>
                </div>
            </div>

            <div class="footer">
                Generated by <a href="https://github.com/mvpetersen/PyPaCER" style="color: inherit;">PyPaCER</a>{f" v{version}" if version else ""} | {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
            </div>
        </div>

        <script>
{_get_javascript()}
        </script>
    </body>
    </html>
    """


def build_3d_plot_html(fig_json: str) -> str:
    """Build the HTML snippet for the 3D Plotly visualization."""
    return f"""
        <div class="plot-3d-container">
            <div id="plot-3d" style="width: 100%; height: 800px;"></div>
        </div>
        <script>
            var plot3dData = {fig_json};
            var plot3dLayout = plot3dData.layout;
            var plot3dTraces = plot3dData.data;

            // Force the layout to use full width
            plot3dLayout.autosize = true;
            plot3dLayout.width = undefined;  // Let Plotly calculate based on container

            var config = {{
                responsive: true,
                displayModeBar: true,
                displaylogo: false,
                toImageButtonOptions: {{
                    format: 'png',
                    filename: 'pypacer_3d_visualization',
                    height: 800,
                    width: 1200,
                    scale: 1
                }}
            }};

            // Create the plot
            Plotly.newPlot('plot-3d', plot3dTraces, plot3dLayout, config);

            // Force an initial resize after a short delay
            setTimeout(function() {{
                Plotly.Plots.resize('plot-3d');
            }}, 100);
        </script>
    """


def _get_css() -> str:
    """Return all CSS styles for the report."""
    return """            body {
                font-family: Arial, sans-serif;
                margin: 20px;
                background-color: #f5f5f5;
            }
            .container {
                max-width: 1600px;
                margin: 0 auto;
                background-color: white;
                padding: 20px;
                border-radius: 10px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            .header {
                text-align: center;
                margin-bottom: 30px;
            }
            .header h1 {
                margin: 0;
                color: #333;
            }
            .header p {
                margin: 5px 0 0 0;
                color: #666;
            }
            /* Tab styling */
            .tabs {
                display: flex;
                border-bottom: 2px solid #ddd;
                margin-bottom: 20px;
            }
            .tab {
                padding: 10px 20px;
                cursor: pointer;
                background-color: #f8f9fa;
                border: 1px solid #ddd;
                border-bottom: none;
                margin-right: 5px;
                border-radius: 5px 5px 0 0;
                transition: background-color 0.3s;
            }
            .tab:hover {
                background-color: #e9ecef;
            }
            .tab.active {
                background-color: white;
                border-bottom: 2px solid white;
                margin-bottom: -2px;
                font-weight: bold;
            }
            .tab-content {
                display: none;
            }
            .tab-content.active {
                display: block;
            }
            /* Original styles */
            .summary {
                margin-bottom: 30px;
                padding: 20px;
                background-color: #f8f9fa;
                border-radius: 8px;
                border-left: 4px solid #007bff;
            }
            .summary h2 {
                margin-top: 0;
                color: #333;
            }
            .summary-grid {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                gap: 20px;
                margin-top: 15px;
            }
            .summary-item {
                padding: 15px;
                background-color: white;
                border-radius: 5px;
                box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            }
            .summary-item h3 {
                margin: 0 0 10px 0;
                color: #007bff;
                font-size: 14px;
            }
            .summary-item p {
                margin: 0;
                font-size: 18px;
                font-weight: bold;
            }
            .plot-section {
                margin-bottom: 30px;
                padding: 20px;
                background-color: #f8f9fa;
                border-radius: 8px;
            }
            .plot-3d-container {
                width: 100%;
                padding: 0;
                margin: 0;
            }
            .electrode-details {
                margin-top: 20px;
            }
            .electrode-card {
                position: relative;
                margin-bottom: 20px;
                padding: 20px;
                background-color: #f8f9fa;
                border-radius: 8px;
                border: 1px solid #ddd;
            }
            .electrode-card h4 {
                margin: 0 0 15px 0;
                color: #333;
                font-size: 18px;
            }
            .electrode-content {
                display: grid;
                grid-template-columns: 300px 1fr;
                gap: 30px;
            }
            .contact-details {
                background-color: white;
                padding: 15px;
                border-radius: 5px;
                box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            }
            .contact-list {
                margin-top: 10px;
            }
            .contact-item {
                display: grid;
                grid-template-columns: 80px 80px auto;
                gap: 10px;
                padding: 5px 0;
                border-bottom: 1px solid #eee;
                align-items: center;
            }
            .contact-item:last-child {
                border-bottom: none;
            }
            .contact-item span:last-child {
                font-family: 'Courier New', monospace;
                color: #555;
            }
            .contact-3d-list {
                margin-top: 8px;
            }
            .contact-3d-item {
                display: flex;
                gap: 10px;
                padding: 3px 0;
                font-size: 12px;
            }
            .contact-3d-item span:first-child {
                min-width: 30px;
                font-weight: 600;
            }
            .contact-3d-item span:last-child {
                font-family: 'Courier New', monospace;
                color: #555;
                white-space: nowrap;
            }
            .intensity-plot {
                background-color: white;
                padding: 10px;
                border-radius: 5px;
                box-shadow: 0 1px 3px rgba(0,0,0,0.1);
                min-height: 400px;
                position: relative;
            }
            .method-btn {
                padding: 5px 12px;
                border: 1px solid #ddd;
                background-color: white;
                border-radius: 4px;
                cursor: pointer;
                font-size: 12px;
                transition: all 0.2s;
            }
            .method-btn:hover {
                background-color: #f0f0f0;
            }
            .method-btn-active {
                background-color: #007bff;
                color: white;
                border-color: #007bff;
            }
            .method-btn-active:hover {
                background-color: #0056b3;
            }
            /* JSON display styling */
            .json-container {
                background-color: #f8f9fa;
                padding: 20px;
                border-radius: 8px;
                overflow-x: auto;
            }
            .json-content {
                background-color: white;
                padding: 20px;
                border-radius: 5px;
                font-family: 'Courier New', monospace;
                font-size: 14px;
                white-space: pre-wrap;
                word-wrap: break-word;
                max-height: 800px;
                overflow-y: auto;
                border: 1px solid #ddd;
            }
            .footer {
                margin-top: 30px;
                padding-top: 20px;
                border-top: 1px solid #ddd;
                text-align: center;
                color: #666;
                font-size: 12px;
            }
            /* Fullscreen modal styles */
            .fullscreen-modal {
                display: none;
                position: fixed;
                z-index: 9999;
                top: 0;
                left: 0;
                width: 100vw;
                height: 100vh;
                background-color: rgba(0, 0, 0, 0.95);
            }
            .fullscreen-modal.active {
                display: block;
            }
            .fullscreen-image-container {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                display: flex;
                justify-content: center;
                align-items: center;
                cursor: pointer;
            }
            .fullscreen-image {
                max-width: 98vw;
                max-height: 98vh;
                width: auto;
                height: auto;
                object-fit: contain;
                cursor: default;
                box-shadow: 0 0 30px rgba(0,0,0,0.8);
            }
            .fullscreen-close {
                position: absolute;
                top: 20px;
                right: 40px;
                color: #fff;
                font-size: 40px;
                font-weight: bold;
                transition: 0.3s;
                cursor: pointer;
                z-index: 1001;
            }
            .fullscreen-close:hover,
            .fullscreen-close:focus {
                color: #bbb;
                text-decoration: none;
                cursor: pointer;
            }
            /* Volume rendering image container with maximize button */
            .volume-image-container {
                position: relative;
                display: block;
                width: 100%;
                text-align: center;
            }
            .volume-image-container img {
                display: inline-block;
                max-width: 100%;
                height: auto;
            }
            .maximize-btn {
                position: absolute;
                top: 10px;
                right: 10px;
                background-color: rgba(255, 255, 255, 0.9);
                border: 1px solid #ddd;
                border-radius: 4px;
                padding: 5px 10px;
                cursor: pointer;
                font-size: 14px;
                transition: all 0.3s;
                z-index: 10;
            }
            .maximize-btn:hover {
                background-color: #007bff;
                color: white;
                border-color: #007bff;
            }
            .maximize-btn svg {
                width: 16px;
                height: 16px;
                vertical-align: middle;
            }"""


def _get_javascript() -> str:
    """Return all JavaScript for the report."""
    return """            function showTab(tabName) {
                // Hide all tabs
                const tabs = document.querySelectorAll('.tab-content');
                tabs.forEach(tab => {
                    tab.classList.remove('active');
                });

                // Remove active class from all tab buttons
                const tabButtons = document.querySelectorAll('.tab');
                tabButtons.forEach(button => {
                    button.classList.remove('active');
                });

                // Show selected tab
                document.getElementById(tabName).classList.add('active');

                // Add active class to clicked tab button
                event.target.classList.add('active');

                // If showing the 3D visualization tab, trigger a resize
                if (tabName === 'visualization3d') {
                    setTimeout(function() {
                        window.dispatchEvent(new Event('resize'));
                        Plotly.Plots.resize('plot-3d');
                    }, 100);
                }

                // Volume tab doesn't need special handling as it uses static images
            }

            // Also trigger resize on window resize
            window.addEventListener('resize', function() {
                if (document.getElementById('visualization3d').classList.contains('active')) {
                    Plotly.Plots.resize('plot-3d');
                }
            });

            // Fullscreen image functionality
            let fullscreenModal = null;

            function createFullscreenModal() {
                if (!fullscreenModal) {
                    fullscreenModal = document.createElement('div');
                    fullscreenModal.className = 'fullscreen-modal';
                    fullscreenModal.innerHTML = `
                        <span class="fullscreen-close">&times;</span>
                        <div class="fullscreen-image-container">
                            <img class="fullscreen-image">
                        </div>
                    `;
                    document.body.appendChild(fullscreenModal);

                    // Close on modal click
                    fullscreenModal.addEventListener('click', function(e) {
                        if (e.target === fullscreenModal || e.target.className === 'fullscreen-close' || e.target.className === 'fullscreen-image-container') {
                            closeFullscreen();
                        }
                    });

                    // Close on Escape key
                    document.addEventListener('keydown', function(e) {
                        if (e.key === 'Escape' && fullscreenModal.classList.contains('active')) {
                            closeFullscreen();
                        }
                    });
                }
                return fullscreenModal;
            }

            function showFullscreen(imgSrc) {
                const modal = createFullscreenModal();
                const img = modal.querySelector('.fullscreen-image');
                img.src = imgSrc;
                modal.classList.add('active');
                document.body.style.overflow = 'hidden';
            }

            function closeFullscreen() {
                if (fullscreenModal) {
                    fullscreenModal.classList.remove('active');
                    document.body.style.overflow = '';
                }
            }

            // Initialize maximize buttons after page load
            document.addEventListener('DOMContentLoaded', function() {
                // Add click handlers to all maximize buttons
                document.querySelectorAll('.maximize-btn').forEach(btn => {
                    btn.addEventListener('click', function(e) {
                        e.stopPropagation();
                        const img = this.parentElement.querySelector('img');
                        if (img) {
                            showFullscreen(img.src);
                        }
                    });
                });
            });"""
